# Generated by Django 4.2.23 on 2025-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsummary',
            name='summary_text',
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='age_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='application_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='minimum_qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='overall_skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='pay_scale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsummary',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
