# Generated by Django 4.2.23 on 2025-07-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_remove_jobsummary_summary_text_jobsummary_age_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsummary',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='jobsummary',
            name='pay_scale',
        ),
        migrations.RemoveField(
            model_name='jobsummary',
            name='pdf_name',
        ),
    ]
