# Generated by Django 4.2.23 on 2025-07-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0003_remove_jobsummary_age_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('minimum_qualification', models.TextField(blank=True, null=True)),
                ('overall_skill', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=255)),
                ('pdf_url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('age_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('application_deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_scale', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='JobSummary',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scraper.source'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdetails', to='Scraper.jobposting'),
        ),
    ]
