# Generated by Django 4.2.23 on 2025-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0004_jobdetails_jobposting_source_delete_jobsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
