# Generated by Django 4.2.23 on 2025-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0006_jobdetails_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='minimum_qualification',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='overall_skill',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='pay_scale',
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='summary',
            field=models.TextField(default='No summary available'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='pdf_url',
            field=models.URLField(unique=True),
        ),
    ]
